const japaneseQuestions = [
  {
    id: 81,
    category: "Japanese",
    question: "What does the kanji 火 (hi) mean?",
    options: ["Fire", "Water", "Tree", "Earth"],
    answer: "Fire",
  },
  {
    id: 82,
    category: "Japanese",
    question: "Which hiragana character represents 'su'?",
    options: ["す", "さ", "せ", "し"],
    answer: "す",
  },
  {
    id: 83,
    category: "Japanese",
    question: "What does the word 先生 (sensei) mean?",
    options: ["Student", "Teacher", "Doctor", "Friend"],
    answer: "Teacher",
  },
  {
    id: 84,
    category: "Japanese",
    question: "Which particle is used as a direct object marker?",
    options: ["が", "を", "は", "に"],
    answer: "を",
  },
  {
    id: 85,
    category: "Japanese",
    question: "What does 日本語 (Nihongo) mean?",
    options: ["Japanese language", "Japan country", "Japanese people", "Tokyo"],
    answer: "Japanese language",
  },
  {
    id: 86,
    category: "Japanese",
    question: "What is the reading of the kanji 月?",
    options: ["tsuki", "mizu", "hi", "yama"],
    answer: "tsuki",
  },
  {
    id: 87,
    category: "Japanese",
    question: "Which katakana character represents 'a'?",
    options: ["ア", "イ", "ウ", "エ"],
    answer: "ア",
  },
  {
    id: 88,
    category: "Japanese",
    question: "What does 学校 (gakkou) mean?",
    options: ["School", "Library", "Teacher", "Student"],
    answer: "School",
  },
  {
    id: 89,
    category: "Japanese",
    question: "What is the polite form of 'to eat'?",
    options: ["食べます", "飲みます", "行きます", "見ます"],
    answer: "食べます",
  },
  {
    id: 90,
    category: "Japanese",
    question: "Which hiragana is 'no'?",
    options: ["の", "ぬ", "ね", "な"],
    answer: "の",
  },
  {
    id: 91,
    category: "Japanese",
    question: "What is the meaning of 友達 (tomodachi)?",
    options: ["Friend", "Family", "Teacher", "Enemy"],
    answer: "Friend",
  },
  {
    id: 92,
    category: "Japanese",
    question: "What is the reading of 山?",
    options: ["yama", "kawa", "mizu", "mori"],
    answer: "yama",
  },
  {
    id: 93,
    category: "Japanese",
    question:
      "Which particle is commonly used to indicate location where an action occurs?",
    options: ["で (de)", "を (wo)", "が (ga)", "と (to)"],
    answer: "で (de)",
  },
  {
    id: 94,
    category: "Japanese",
    question: "What does 電車 (densha) mean?",
    options: ["Train", "Car", "Bicycle", "Bus"],
    answer: "Train",
  },
  {
    id: 95,
    category: "Japanese",
    question: "Which kanji means 'tree'?",
    options: ["木", "山", "川", "空"],
    answer: "木",
  },
  {
    id: 96,
    category: "Japanese",
    question: "What is the reading of 水?",
    options: ["mizu", "hi", "yama", "tsuki"],
    answer: "mizu",
  },
  {
    id: 97,
    category: "Japanese",
    question: "Which hiragana is 'ta'?",
    options: ["た", "ち", "つ", "て"],
    answer: "た",
  },
  {
    id: 98,
    category: "Japanese",
    question: "What does 勉強 (benkyou) mean?",
    options: ["Study", "Sleep", "Work", "Play"],
    answer: "Study",
  },
  {
    id: 99,
    category: "Japanese",
    question: "What does 東京 (Tokyo) literally mean?",
    options: ["Eastern Capital", "Big City", "Sky City", "Sun City"],
    answer: "Eastern Capital",
  },
  {
    id: 100,
    category: "Japanese",
    question: "What does 車 (kuruma) mean?",
    options: ["Car", "Train", "Bicycle", "Plane"],
    answer: "Car",
  },
];

export default japaneseQuestions;
